package biochemie.linx;

/**
 *
 * @author kuan
 */
public class AboutDialog extends javax.swing.JDialog {

	String versionString;

	/**
	 * Creates new form AboutDialog
	 *
	 * @param parent
	 * @param version
	 */
	public AboutDialog(java.awt.Frame parent, String version) {
		super(parent, true);
		this.versionString = version;
		initComponents();
		this.setLocationRelativeTo(parent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      logoLb = new javax.swing.JLabel();
      label1Lb = new javax.swing.JLabel();
      label2Lb = new javax.swing.JLabel();
      mailTF = new javax.swing.JTextField();
      versionLb = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("About LinX");
      setResizable(false);

      logoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      logoLb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biochemie/linx/dialogLogo.png"))); // NOI18N

      label1Lb.setText("Please feel free to send us any comments or bug reports.");

      label2Lb.setText("For this purpose please use following mail address.");

      mailTF.setEditable(false);
      mailTF.setText("zdenek.kukacka@biomed.cas.cz");

      versionLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      versionLb.setText("LinX version " + versionString);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(versionLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(logoLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(label1Lb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(label2Lb, javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(mailTF, javax.swing.GroupLayout.Alignment.LEADING))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(logoLb)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(versionLb)
            .addGap(18, 18, 18)
            .addComponent(label1Lb)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(label2Lb)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(mailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel label1Lb;
   private javax.swing.JLabel label2Lb;
   private javax.swing.JLabel logoLb;
   private javax.swing.JTextField mailTF;
   private javax.swing.JLabel versionLb;
   // End of variables declaration//GEN-END:variables
}
